#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# init.sh — AI agent instruction sync
#
# Source of truth: .roo/rules/  (do NOT edit the generated files manually!)
# Regenerate by running this script any time .roo/rules/ changes.
#
# Generates the agent-specific instruction file for ONE of:
#   1) GitHub Copilot  -> .github/copilot-instructions.md
#   2) Cursor          -> .cursor/rules/project.mdc
#   3) Claude Code     -> CLAUDE.md
#
# Behaviour:
#   - Interactive only (no CLI flags) — picks one agent per run.
#   - Idempotent: if the target file is identical, nothing is written.
#   - Single .bak is kept next to the target (always overwritten on save).
#   - .gitignore is appended with an "AI agent instruction files" section
#     (idempotent — entries are not duplicated).
#   - Old files for a different agent are left in place (user can switch back).
#
# Exit codes:
#   0 = success / user chose quit
#   1 = fatal error (.roo/rules/ missing, no readable source files, etc.)
# ------------------------------------------------------------------------------

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants — fixed paths so the script is portable and reviewable.
# ---------------------------------------------------------------------------

readonly SCRIPT_NAME="init.sh"
readonly RULES_DIR=".roo/rules"

# These are the 3 single-source-of-truth files. Order is the output order.
readonly -a SOURCE_FILES=(
  "instructions.md"
  "general.coding-standards.md"
  "project-context.md"
)

# Maps "agent key" -> relative target path + format.
# "format" = "md" (raw markdown) or "mdc" (frontmatter prepended).
readonly -A AGENT_TARGETS=(
  ["copilot"]=".github/copilot-instructions.md|md"
  ["cursor"]=".cursor/rules/project.mdc|mdc"
  ["claude"]="CLAUDE.md|md"
)

readonly GITIGNORE_FILE=".gitignore"
readonly GITIGNORE_MARKER="# --- AI agent instruction files (autogenerated by scripts/init.*) ---"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log_info()  { printf '\033[36m[i]\033[0m %s\n' "$*"; }
log_ok()    { printf '\033[32m[+]\033[0m %s\n' "$*"; }
log_warn()  { printf '\033[33m[!]\033[0m %s\n' "$*"; }
log_error() { printf '\033[31m[x]\033[0m %s\n' "$*" >&2; }

# Portable "does file exist?" check (avoids `[[ ... ]]` for POSIX-sh users
# who may source this file).
has_file() { test -f "$1"; }

# Read file into a variable without losing trailing newlines.
read_file() {
  local f="$1"
  # `cat` followed by `$()` strips trailing newlines; compensate by adding one.
  # That's safe because the source files already end with a newline anyway.
  cat "$f"
  # Ensure trailing newline.
  printf '\n'
}

# ---------------------------------------------------------------------------
# Pre-flight: workspace + source files
# ---------------------------------------------------------------------------

cd_to_repo_root() {
  # Walk upwards until we find the RULES_DIR. This lets the script run from
  # any subdirectory inside the monorepo.
  local dir
  dir="$(pwd)"
  while true; do
    if [[ -d "${dir}/${RULES_DIR}" ]]; then
      cd "${dir}"
      return 0
    fi
    if [[ "${dir}" == "/" || -z "${dir}" ]]; then
      return 1
    fi
    dir="$(dirname "${dir}")"
  done
}

check_source_files() {
  local missing=()
  local present=()
  for f in "${SOURCE_FILES[@]}"; do
    if has_file "${RULES_DIR}/${f}"; then
      present+=("${RULES_DIR}/${f}")
    else
      missing+=("${RULES_DIR}/${f}")
    fi
  done

  # Logging must go to STDERR — the caller captures this function's stdout
  # via $(...) to read the file list, so any stdout noise would corrupt it.
  for f in "${present[@]}"; do
    log_info "Forrás: ${f}" >&2
  done
  for f in "${missing[@]}"; do
    log_warn "Hiányzó forrás (kihagyva): ${f}" >&2
  done

  if [[ ${#present[@]} -eq 0 ]]; then
    log_error "Egyetlen forrásfájl sem olvasható a ${RULES_DIR}/ alatt." >&2
    return 1
  fi

  # Echo present files, one per line, on STDOUT for the caller to consume.
  printf '%s\n' "${present[@]}"
}

# ---------------------------------------------------------------------------
# Content assembly
# ---------------------------------------------------------------------------

build_content() {
  local format="$1"
  shift
  local present_files=("$@")

  local body=""
  for src in "${present_files[@]}"; do
    body+=$'\n---\n\n'
    body+="## Source: ${src}"$'\n\n'
    body+="$(read_file "${src}")"
  done

  # Trim leading newline from the first separator for cleanliness.
  body="${body#$'\n'}"

  local header
  header="# AI Agent Instructions \xe2\x80\x94 autogenerated from .roo/rules/"$'\n\n'
  header+="<!-- DO NOT EDIT THIS FILE MANUALLY. -->"$'\n'
  header+="<!-- Source of truth: .roo/rules/ \xe2\x80\x94 edit those files instead. -->"$'\n'
  header+="<!-- Regenerate by running: scripts/${SCRIPT_NAME} (or scripts/init.ps1 on Windows) -->"$'\n'

  local out=""
  if [[ "${format}" == "mdc" ]]; then
    # Cursor MDC frontmatter.
    out+="---"$'\n'
    out+="description: AIsztens \xe2\x80\x94 project + coding rules (autogenerated from .roo/rules/)"$'\n'
    out+="globs:"$'\n'
    out+="alwaysApply: true"$'\n'
    out+="---"$'\n\n'
    out+="${header}"
    out+="${body}"
  else
    # Plain markdown header.
    out+="${header}"
    out+="${body}"
  fi

  printf '%s' "${out}"
}

# ---------------------------------------------------------------------------
# Target file write + .bak logic
# ---------------------------------------------------------------------------

write_target() {
  local target="$1"
  local content="$2"

  mkdir -p "$(dirname "${target}")"

  if has_file "${target}"; then
    local existing
    existing="$(cat "${target}")"
    if [[ "${existing}" == "${content}" ]]; then
      log_ok "A célfájl már naprakész, nincs teendő: ${target}"
      return 0
    fi

    # Content differs -> save the .bak (single, always overwritten).
    local bak="${target}.bak"
    cp -f "${target}" "${bak}"
    log_warn "Régi tartalom elmentve: ${bak}"
  fi

  printf '%s' "${content}" > "${target}"
  log_ok "Célfájl írva: ${target}"
}

# ---------------------------------------------------------------------------
# .gitignore management
# ---------------------------------------------------------------------------

ensure_gitignore_entry() {
  local path="$1"

  if [[ ! -f "${GITIGNORE_FILE}" ]]; then
    log_warn "${GITIGNORE_FILE} nem létezik \xe2\x80\x94 kézzel add hozzá: ${path}"
    return 0
  fi

  # Check whether the path is already listed.
  if grep -qxF "${path}" "${GITIGNORE_FILE}"; then
    return 0
  fi

  # Append the marker + the path (only first time creates the section).
  if ! grep -qxF "${GITIGNORE_MARKER}" "${GITIGNORE_FILE}"; then
    printf '\n%s\n' "${GITIGNORE_MARKER}" >> "${GITIGNORE_FILE}"
    printf '# Source of truth: .roo/rules/\n' >> "${GITIGNORE_FILE}"
  fi
  printf '%s\n' "${path}" >> "${GITIGNORE_FILE}"
  log_ok "${GITIGNORE_FILE} frissítve: ${path}"
}

ensure_gitignore_backup_entry() {
  local target="$1"
  ensure_gitignore_entry "${target}.bak"
}

# ---------------------------------------------------------------------------
# Interactive prompt
# ---------------------------------------------------------------------------

prompt_agent() {
  local max_attempts=5
  local attempt=1

  while [[ ${attempt} -le ${max_attempts} ]]; do
    # CRITICAL: write the menu to STDERR, not stdout. The return value is
    # captured via $(prompt_agent), so anything on stdout would be eaten by
    # command substitution. Using >&2 keeps the prompt visible to the user.
    {
      printf '\n'
      log_info "Melyik AI coding agentet használod?"
      printf '   1) GitHub Copilot  -> %s\n' "${AGENT_TARGETS[copilot]%%|*}"
      printf '   2) Cursor          -> %s\n' "${AGENT_TARGETS[cursor]%%|*}"
      printf '   3) Claude Code     -> %s\n' "${AGENT_TARGETS[claude]%%|*}"
      printf '   q) Quit (kilépés, semmi nem változik)\n'
      printf '\nVálasz [1/2/3/q]: '
    } >&2

    local choice
    if ! IFS= read -r choice; then
      log_warn "Nincs elérhető input (stdin zárva). Kilépés." >&2
      printf 'quit'
      return 0
    fi

    case "${choice}" in
      1|copilot|Copilot|GITHUB|COPILOT) printf 'copilot'; return 0 ;;
      2|cursor|Cursor|CURSOR)           printf 'cursor';  return 0 ;;
      3|claude|Claude|CLAUDE)           printf 'claude';  return 0 ;;
      q|Q|quit|Quit)                    printf 'quit';   return 0 ;;
      "")
        attempt=$((attempt + 1))
        continue
        ;;
      *)
        log_warn "Ismeretlen válasz: '${choice}'." >&2
        attempt=$((attempt + 1))
        continue
        ;;
    esac
  done

  log_warn "Túl sok érvénytelen próbálkozás (${max_attempts}). Kilépés." >&2
  printf 'quit'
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
  if ! cd_to_repo_root; then
    log_error "Nem találom a ${RULES_DIR}/ mappát a workspace gyökerében. Futtasd a projekt gyökeréből."
    exit 1
  fi
  log_info "Repo gyökér: $(pwd)"

  printf '\n--- Forrásfájlok (single source of truth: %s) ---\n' "${RULES_DIR}"
  local present_list
  present_list="$(check_source_files)" || exit 1

  # Convert the newline-separated list into a bash array.
  local present_files=()
  while IFS= read -r line; do
    [[ -n "${line}" ]] && present_files+=("${line}")
  done <<< "${present_list}"

  printf '\n--- Melyik AI agent? ---\n'
  local agent
  agent="$(prompt_agent)"
  if [[ "${agent}" == "quit" ]]; then
    log_info "Kilépés, semmi nem változott."
    exit 0
  fi

  local spec="${AGENT_TARGETS[${agent}]}"
  local target="${spec%%|*}"
  local format="${spec##*|}"

  printf '\n--- Összefűzés + írás ---\n'
  local content
  content="$(build_content "${format}" "${present_files[@]}")"
  write_target "${target}" "${content}"

  printf '\n--- .gitignore szinkronizálás ---\n'
  ensure_gitignore_entry "${target}"
  ensure_gitignore_backup_entry "${target}"

  printf '\n'
  log_ok "Kész."
  log_info "Ne feledd: a forrás a ${RULES_DIR}/ \xe2\x80\x94 ne szerkeszd a generált fájlt."
  log_info "Újrafuttatás: scripts/${SCRIPT_NAME} (vagy scripts/init.ps1 Windows-on)."
}

main "$@"
