<#
.SYNOPSIS
    init.ps1 - AI agent instruction sync (Windows PowerShell 5.1+ / PowerShell 7+).

.DESCRIPTION
    Source of truth: .roo/rules/  (do NOT edit the generated files manually!)
    Regenerate by running this script any time .roo/rules/ changes.

    Generates the agent-specific instruction file for ONE of:
        1) GitHub Copilot  -> .github/copilot-instructions.md
        2) Cursor          -> .cursor/rules/project.mdc
        3) Claude Code     -> CLAUDE.md

    Behaviour:
        - Interactive only (no CLI flags).
        - Idempotent: if the target file is identical, nothing is written.
        - Single .bak is kept next to the target (always overwritten on save).
        - .gitignore is appended with an "AI agent instruction files" section
          (idempotent - entries are not duplicated).
        - Old files for a different agent are left in place.

.EXITCODE
    0 = success / user chose quit
    1 = fatal error
#>

[CmdletBinding()]
param(
    # Reserved for future flags. Interactive only for now.
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

$ScriptName = 'init.ps1'
$RulesDir   = '.roo/rules'

# Fixed list, in output order.
$SourceFiles = @(
    'instructions.md',
    'general.coding-standards.md',
    'project-context.md'
)

# Agent key -> @{ Target = 'rel/path'; Format = 'md' | 'mdc' }
$AgentTargets = @{
    'copilot' = @{ Target = '.github/copilot-instructions.md'; Format = 'md'  }
    'cursor'  = @{ Target = '.cursor/rules/project.mdc';        Format = 'mdc' }
    'claude'  = @{ Target = 'CLAUDE.md';                       Format = 'md'  }
}

$GitignoreFile       = '.gitignore'
$GitignoreMarker     = '# --- AI agent instruction files (autogenerated by scripts/init.*) ---'
$GitignoreSourceLine = '# Source of truth: .roo/rules/'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Write-Info  { param([string]$Msg) Write-Host "[i] $Msg" -ForegroundColor Cyan }
function Write-Ok    { param([string]$Msg) Write-Host "[+] $Msg" -ForegroundColor Green }
function Write-Warn  { param([string]$Msg) Write-Host "[!] $Msg" -ForegroundColor Yellow }
function Write-Err   { param([string]$Msg) [Console]::Error.WriteLine("[x] $Msg") }

function Test-File {
    param([string]$Path)
    return Test-Path -LiteralPath $Path -PathType Leaf
}

# Walk upwards to find $RulesDir (lets the script run from any subdirectory).
function Resolve-RepoRoot {
    param([string]$StartDir)
    $dir = (Resolve-Path -LiteralPath $StartDir).ProviderPath
    while ($true) {
        if (Test-Path -LiteralPath (Join-Path $dir $RulesDir) -PathType Container) {
            return $dir
        }
        $parent = Split-Path -LiteralPath $dir -Parent
        if ([string]::IsNullOrEmpty($parent) -or $parent -eq $dir) {
            return $null
        }
        $dir = $parent
    }
}

# ---------------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------------

function Get-PresentSourceFiles {
    $present = New-Object System.Collections.Generic.List[string]
    foreach ($f in $SourceFiles) {
        $p = Join-Path $RulesDir $f
        if (Test-File $p) {
            Write-Info "Forrás: $p"
            $present.Add($p) | Out-Null
        } else {
            Write-Warn "Hiányzó forrás (kihagyva): $p"
        }
    }
    if ($present.Count -eq 0) {
        Write-Err "Egyetlen forrásfájl sem olvasható a $RulesDir/ alatt."
        return $null
    }
    return $present
}

# ---------------------------------------------------------------------------
# Content assembly
# ---------------------------------------------------------------------------

function Build-Content {
    param(
        [string]$Format,
        [System.Collections.Generic.List[string]]$PresentFiles
    )

    $body = ''
    foreach ($src in $PresentFiles) {
        $body += "`n---`n`n"
        $body += "## Source: $src`n`n"
        $body += (Get-Content -LiteralPath $src -Raw -Encoding UTF8)
        if (-not $body.EndsWith("`n")) { $body += "`n" }
    }
    # Strip the leading newline from the first separator for cleanliness.
    $body = $body.TrimStart("`n")

    $emDash = [char]0x2014
    $header  = "# AI Agent Instructions $emDash autogenerated from .roo/rules/`n`n"
    $header += "<!-- DO NOT EDIT THIS FILE MANUALLY. -->`n"
    $header += "<!-- Source of truth: .roo/rules/ $emDash edit those files instead. -->`n"
    $header += "<!-- Regenerate by running: scripts/init.ps1 (or scripts/init.sh on Linux/macOS) -->`n"

    if ($Format -eq 'mdc') {
        $out  = "---`n"
        $out += "description: AIsztens $emDash project + coding rules (autogenerated from .roo/rules/)`n"
        $out += "globs:`n"
        $out += "alwaysApply: true`n"
        $out += "---`n`n"
        $out += $header
        $out += $body
        return $out
    }
    else {
        return ($header + $body)
    }
}

# ---------------------------------------------------------------------------
# Target file write + .bak logic
# ---------------------------------------------------------------------------

function Write-Target {
    param(
        [string]$Path,
        [string]$Content
    )

    $dir = Split-Path -LiteralPath $Path -Parent
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -LiteralPath $dir -Force | Out-Null
    }

    if (Test-File $Path) {
        $existing = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
        if ($existing -eq $Content) {
            Write-Ok "A célfájl már naprakész, nincs teendő: $Path"
            return
        }
        $bak = "$Path.bak"
        Copy-Item -LiteralPath $Path -Destination $bak -Force
        Write-Warn "Régi tartalom elmentve: $bak"
    }

    Set-Content -LiteralPath $Path -Value $Content -NoNewline -Encoding UTF8
    Write-Ok "Célfájl írva: $Path"
}

# ---------------------------------------------------------------------------
# .gitignore management
# ---------------------------------------------------------------------------

function Ensure-GitignoreEntry {
    param([string]$Path)

    if (-not (Test-File $GitignoreFile)) {
        Write-Warn "$GitignoreFile nem létezik - kézzel add hozzá: $Path"
        return
    }

    $lines = Get-Content -LiteralPath $GitignoreFile -Encoding UTF8
    foreach ($l in $lines) {
        if ($l -eq $Path) { return }
    }

    $hasMarker = $false
    foreach ($l in $lines) { if ($l -eq $GitignoreMarker) { $hasMarker = $true; break } }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine(($lines -join "`n"))
    if (-not $hasMarker) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine($GitignoreMarker)
        [void]$sb.AppendLine($GitignoreSourceLine)
    }
    [void]$sb.AppendLine($Path)

    Set-Content -LiteralPath $GitignoreFile -Value ($sb.ToString()).TrimEnd("`r","`n") -Encoding UTF8
    Write-Ok "$GitignoreFile frissítve: $Path"
}

function Ensure-GitignoreBackupEntry {
    param([string]$Path)
    Ensure-GitignoreEntry "$Path.bak"
}

# ---------------------------------------------------------------------------
# Interactive prompt
# ---------------------------------------------------------------------------

function Prompt-Agent {
    Write-Host ''
    Write-Info 'Melyik AI coding agentet használod?'
    Write-Host ('   1) GitHub Copilot  -> {0}' -f $AgentTargets['copilot'].Target)
    Write-Host ('   2) Cursor          -> {0}' -f $AgentTargets['cursor'].Target)
    Write-Host ('   3) Claude Code     -> {0}' -f $AgentTargets['claude'].Target)
    Write-Host '   q) Quit (kilépés, semmi nem változik)'
    Write-Host ''
    $choice = (Read-Host 'Válasz [1/2/3/q]').Trim()

    switch -Regex ($choice) {
        '^(1|copilot|Copilot|GITHUB|COPILOT)$' { return 'copilot' }
        '^(2|cursor|Cursor|CURSOR)$'           { return 'cursor' }
        '^(3|claude|Claude|CLAUDE)$'           { return 'claude' }
        '^(q|Q|quit|Quit)$'                    { return 'quit' }
        default {
            Write-Warn "Ismeretlen válasz: '$choice'. Újra kérdezem."
            return (Prompt-Agent)
        }
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

try {
    $repoRoot = Resolve-RepoRoot -StartDir (Get-Location).ProviderPath
    if (-not $repoRoot) {
        Write-Err "Nem találom a $RulesDir/ mappát a workspace gyökerében. Futtasd a projekt gyökeréből."
        exit 1
    }
    Set-Location -LiteralPath $repoRoot
    Write-Info "Repo gyökér: $(Get-Location)"

    Write-Host ''
    Write-Host "--- Forrásfájlok (single source of truth: $RulesDir) ---"
    $present = Get-PresentSourceFiles
    if ($null -eq $present) { exit 1 }

    Write-Host ''
    Write-Host '--- Melyik AI agent? ---'
    $agent = Prompt-Agent
    if ($agent -eq 'quit') {
        Write-Info 'Kilépés, semmi nem változott.'
        exit 0
    }

    $spec    = $AgentTargets[$agent]
    $target  = $spec.Target
    $format  = $spec.Format

    Write-Host ''
    Write-Host '--- Összefűzés + írás ---'
    $content = Build-Content -Format $format -PresentFiles $present
    Write-Target -Path $target -Content $content

    Write-Host ''
    Write-Host '--- .gitignore szinkronizálás ---'
    Ensure-GitignoreEntry    -Path $target
    Ensure-GitignoreBackupEntry -Path $target

    Write-Host ''
    $emDash = [char]0x2014
    Write-Ok 'Kész.'
    Write-Info "Ne feledd: a forrás a $RulesDir/ $emDash ne szerkeszd a generált fájlt."
    Write-Info 'Újrafuttatás: scripts/init.ps1 (vagy scripts/init.sh Linux/macOS alatt).'
}
catch {
    Write-Err "Váratlan hiba: $($_.Exception.Message)"
    exit 1
}
